language: php

dist: trusty

matrix:
  include:
    - php: 7.3
      env: ANALYSIS='true'
    - php: 7.4

  allow_failures:
    - php: 7.4

before_script:
  - if [[ "$ANALYSIS" == 'true' ]]; then composer require php-coveralls/php-coveralls:^2.2.0 ; fi
  - composer install -n

script:
  - if [[ "$ANALYSIS" != 'true' ]]; then vendor/bin/phpunit ; fi
  - if [[ "$ANALYSIS" == 'true' ]]; then vendor/bin/phpunit --coverage-clover clover.xml ; fi

after_success:
  - if [[ "$ANALYSIS" == 'true' ]]; then vendor/bin/php-coveralls --coverage_clover=clover.xml -v ; fi
